# Gradle
org.gradle.jvmargs=-Xmx4G

# Project
version=1.0.0.0
last_mod_version=0.1.0.0
group=com.github.wendall911.tunneltrench

# Common
minecraft_version=26.1.2
mixin_extras_version=0.5.3
whitenoise_version=2.2.1
whitenoise_range=[2.2.1,3.0.0)
fabric_whitenoise_range=[">=2.2.1","<=3.0.0"]
mixin_version=0.8.5
java_version=25

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.43-beta
neoforge_loader_version_range=[11,)
neoforge_version_range=[26.1.2.21-beta,)
neoforge_mc_version_range=[26.1, 26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.148.0+26.1.2
fabric_api_min_version=>=0.143.10
fabric_loader_version=0.19.2
fabric_loader_min_version=>=0.15
fabric_mc_version_range=[">26.1-"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=18.0.0-alpha.8

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=29.5.0.26
jei_minecraft_version=26.1.2

# Mod options
mod_display_name=Tunnel & Trench
mod_name=TunnelTrench
mod_id=tunneltrench
mod_author=wendall911
mod_credits=Knoface, Other Buggy Mods, and the Minecraft modding community.
license=MIT
mod_description=Vanilla friendly 3x3 mining hammers and shovels.
mod_update_branch=26.1

# CurseForge/Modrinth Options
# Global properties are located in ~/.gradle/gradle.properties
# DO NOT put private keys here
curseforge_api_key_prop=ttcurseApiKey
curseforge_id=XXXXXX
curseforge_slug=tunnel-trench
modrinth_api_key_prop=modrinthKey
modrinth_id=XXXXXX
discord_webhook_prop=ttDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=26.1,26.1.1,26.1.2
